version: '3.7'
include:
   - infra.yaml
services:
    app:
        build: ./
        command: streamlit run financa.py --server.port 8501
        volumes:
            - ./:/usr/src/app
        ports:
            - 8501:8501
        image: yourstreamlitapp:latest
        networks:
            rasa-networks:
networks:
  rasa-networks: